default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { 'password' } %>
  database: r01

development:
  <<: *default
  host: mysql

test:
  <<: *default
  host: mysql_test

production:
  <<: *default
  host: mysql
