name: build-ruby-docker-image

on:
  push:
    paths:
      - '.github/workflows/build-ruby-docker-image.yml'
      - '.docker/ruby/**/*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: 3.2.0
            debian-version: bullseye
            bundler-version: 2.4.1
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./.docker/ruby
          build-args: |
            RUBY_VERSION=${{ matrix.ruby-version }}
            DEBIAN_VERSION=${{ matrix.debian-version }}
            BUNDLER_VERSION=${{ matrix.bundler-version }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ruby:${{ matrix.ruby-version }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/ruby:${{ matrix.ruby-version }}-build-cache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/ruby:${{ matrix.ruby-version }}-build-cache,mode=max
